name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: go fmt
      run: "test -z $(go fmt ./...)"

    - name: go generate
      run: go generate -v ./...

    - name: go build
      run: go build -v ./...

    - name: go test
      run: go test -v ./...

    - name: go test -race
      run: go test -race ./...
